# Generated by Django 2.2.10 on 2020-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20200812_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.TextField(choices=[('iphonee-x', 'Iphone X'), ('samsung-galaxy-edge-2', 'Samsung Galaxy Edge 2'), ('nokia-8', 'Nokia 8')], null=True),
        ),
    ]
